server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  # SPA: rotas do Angular caem no index.html.
  location / {
    try_files $uri $uri/ /index.html;
  }

  # API REST do painel administrativo (RF14/RF15) -> backend (mesma origem).
  location /admin/ {
    proxy_pass http://backend:3000;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  # Tempo real: encaminha o WebSocket/Socket.IO para o backend (mesma origem).
  location /socket.io/ {
    proxy_pass http://backend:3000;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}
